const userData = {
  githubUsername: "JayRmz",
  name: "Jay Ramirez",
  designation: "Mobile & Full-Stack Developer",
  avatarUrl: "/avatar.jpeg",
  email: "ramirezblancasjuanm@gmail.com",
  phone: "+528126375939",
  address: "México.",
  projects: [
    {
      title: "Mknicar",
      link: "https://www.mknicar.com.mx/",
      imgUrl: "/mknicar.png",
    },
    {
      title: "Fielder Agente",
      link: "https://www.appfielder.com/#app",
      imgUrl: "/fielder.png",
    },
    {
      title: "Jalas",
      link: "https://jalas.mx/",
      imgUrl: "/jalas.png",
    },
    {
      title: "iTrackU V2 iOS",
      link: "https://apps.apple.com/mx/app/itracku-v2/id1543451470",
      imgUrl: "/itracku.png",
    },
    {
      title: "iTrackU V2 Android",
      link: "https://play.google.com/store/apps/details?id=mobi.digitalfactory.itracku",
      imgUrl: "/itracku.png",
    },
    {
      title: "Roller Pack",
      link: "https://play.google.com/store/apps/details?id=mx.eiimt.rollerlog",
      imgUrl: "/roller.png",
    },
  ],
  about: {
    title: "I'm a mobile app developer & full-stack web developer",
    description: [
      `My journey developing apps started on 2018 with an Android 8 development course with Java.`,
      `Ever since then I love the mobile world, and as I love to improve myself, I kept learning and learning languages and frameworks like Ionic, Angular, JavaScript, Typescript & Swift being this last one, the one that I love the most.`,
      `Most of my professional journey has been developing iOS apps with Swift & SwiftUI, but one of my biggest projects was developed with the use of Ionic, NodeJS, MySQL & the usage of AWS and Digital Ocean.`,
    ],
  },
  experience: [
    {
      id: 8,
      title: "Mobile App developer",
      company: "NextCloud",
      year: "2022 - Current",
      companyLink: "https://www.next-cloud.mx",
      desc: "Hybrid and native mobile app developer.",
      apps: "Warehouse",
    },
    {
      id: 7,
      title: "Frontend developer",
      company: "Cicada Securities",
      year: "2021 - 2022",
      companyLink: "https://cicada.io/",
      desc: "Frontend development with ReactJS of Mtrade's Trading Platform.",
      apps: "Mtrade Trading Platform",
    },
    {
      id: 5,
      title: "Mobile Developer",
      company: "EIIMT",
      year: "2020 - 2021",
      companyLink: "https://apps.apple.com/mx/app/itracku-v2/id1543451470",
      desc: "Develop & Maintain mobile apps, with the use of Swift, SwiftUI, Kotlin & Ionic.",
      apps: "iTrackU V2 (Android & iOS), iWolet, Roller logistics",
    },
    {
      id: 4,
      title: "Mobile & Full-Stack Developer",
      company: "Jalas",
      year: "2020 - 2021",
      companyLink: "https://jalas.mx/",
      desc: "Developed full Jalas Ecosystem, mobile and web apps with the use of Ionic 5, Backend with NodeJS & MySQL Database.",
      apps: "Jalas, Jalas Sites, Jalas Staff",
    },
    {
      id: 3,
      title: "iOS Developer",
      company: "Smart Service Transformation Consulting S.A. de C.V.",
      year: "2019",
      companyLink: "https://www.appfielder.com/",
      desc: "iOS development for the Fielder Agente app.",
      apps: "Fielder Agente",
    },
    {
      id: 2,
      title: "Project Manager",
      company: "EXIE",
      year: "2018 - 2019",
      companyLink: "https://www.exie.com.mx/",
      desc: "Project Manager & Mobile app developer.",
    },
    {
      id: 1,
      title: "Mobile App Dev (Intern)",
      company: "GYO Solutions",
      year: "2018",
      companyLink: "http://gyo-solutions.com/",
      desc: "Maintain & develop Ionic 3 apps.",
    },
    {
      id: 0,
      title: "Computer Science Engineer",
      company: "Tec de Monterrey (ITESM) Campus Toluca",
      year: "2014 - 2019",
      companyLink: "https://tec.mx/es/toluca",
      desc: "University degree.",
    },
  ],
  resumeUrl:
    "https://drive.google.com/file/d/1NLjFxvWmiUXwUTkuQHsPHIJhNOSr_3ZB/view?usp=sharing",
  socialLinks: {
    instagram: "https://www.instagram.com/jayramirezdev/",
    twitter: "",
    linkedin:
      "https://www.linkedin.com/in/juan-manuel-ram%C3%ADrez-blancas-64a446158/",
    github: "https://github.com/JayRmz",
    facebook: "https://facebook.com/",
    whatsapp: "https://wa.me/528126375939",
  },
};

export default userData;
